try new build

diff --git a/module2_task1/Makefile b/module2_task1/Makefile
--- a/module2_task1/Makefile
+++ b/module2_task1/Makefile
@@ -1,5 +1,9 @@
+lint: ## lint th
+    golangci-lint run
+    if [ $? -ne 0 ]; then echo "Linting failed"; exit 1; else echo "Linting succeeded"; fi
+
 build: ## compile source code and build site
-	go build
+	go build -o myapp main.go
 
 run: ## Run the app in the background and write the logs
 	./awesome-api >./awesome.log 2>&1 &
@@ -15,8 +19,6 @@ test: ## test for functionality
 	curl http://localhost:9999
 	curl http://localhost:9999/health
 
-lint: ## lint the main.go for errors
-	golangci-lint run
 
 Silent: ## test for functionality
 help: ## Print a list of all the goals with a sentence.
